// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by HostArtworkApi.
NSObject<FlutterMessageCodec> *HostArtworkApiGetCodec(void);

@protocol HostArtworkApi
/// @return `nil` only when `error != nil`.
- (nullable FlutterStandardTypedData *)queryArtworkId:(NSString *)id error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpHostArtworkApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HostArtworkApi> *_Nullable api);

NS_ASSUME_NONNULL_END
