// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Audio.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface Song ()
+ (Song *)fromList:(NSArray *)list;
+ (nullable Song *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface Album ()
+ (Album *)fromList:(NSArray *)list;
+ (nullable Album *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation Song
+ (instancetype)makeWithId:(NSString *)id
    title:(NSString *)title
    artist:(NSString *)artist
    imageId:(NSString *)imageId
    duration:(double )duration {
  Song* pigeonResult = [[Song alloc] init];
  pigeonResult.id = id;
  pigeonResult.title = title;
  pigeonResult.artist = artist;
  pigeonResult.imageId = imageId;
  pigeonResult.duration = duration;
  return pigeonResult;
}
+ (Song *)fromList:(NSArray *)list {
  Song *pigeonResult = [[Song alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.title = GetNullableObjectAtIndex(list, 1);
  pigeonResult.artist = GetNullableObjectAtIndex(list, 2);
  pigeonResult.imageId = GetNullableObjectAtIndex(list, 3);
  pigeonResult.duration = [GetNullableObjectAtIndex(list, 4) doubleValue];
  return pigeonResult;
}
+ (nullable Song *)nullableFromList:(NSArray *)list {
  return (list) ? [Song fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.id ?: [NSNull null],
    self.title ?: [NSNull null],
    self.artist ?: [NSNull null],
    self.imageId ?: [NSNull null],
    @(self.duration),
  ];
}
@end

@implementation Album
+ (instancetype)makeWithId:(NSString *)id
    title:(NSString *)title
    artist:(NSString *)artist
    imageId:(NSString *)imageId {
  Album* pigeonResult = [[Album alloc] init];
  pigeonResult.id = id;
  pigeonResult.title = title;
  pigeonResult.artist = artist;
  pigeonResult.imageId = imageId;
  return pigeonResult;
}
+ (Album *)fromList:(NSArray *)list {
  Album *pigeonResult = [[Album alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.title = GetNullableObjectAtIndex(list, 1);
  pigeonResult.artist = GetNullableObjectAtIndex(list, 2);
  pigeonResult.imageId = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable Album *)nullableFromList:(NSArray *)list {
  return (list) ? [Album fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.id ?: [NSNull null],
    self.title ?: [NSNull null],
    self.artist ?: [NSNull null],
    self.imageId ?: [NSNull null],
  ];
}
@end

@interface AlbumHostApiCodecReader : FlutterStandardReader
@end
@implementation AlbumHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [Album fromList:[self readValue]];
    case 129: 
      return [Album fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface AlbumHostApiCodecWriter : FlutterStandardWriter
@end
@implementation AlbumHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[Album class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Album class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface AlbumHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation AlbumHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[AlbumHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[AlbumHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *AlbumHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    AlbumHostApiCodecReaderWriter *readerWriter = [[AlbumHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpAlbumHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AlbumHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.AlbumHostApi.getAllAlbums"
        binaryMessenger:binaryMessenger
        codec:AlbumHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAllAlbumsWithError:)], @"AlbumHostApi api (%@) doesn't respond to @selector(getAllAlbumsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<Album *> *output = [api getAllAlbumsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.AlbumHostApi.getAlbumById"
        binaryMessenger:binaryMessenger
        codec:AlbumHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAlbumByIdId:error:)], @"AlbumHostApi api (%@) doesn't respond to @selector(getAlbumByIdId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        Album *output = [api getAlbumByIdId:arg_id error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *ArtworkHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void SetUpArtworkHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ArtworkHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.ArtworkHostApi.queryArtwork"
        binaryMessenger:binaryMessenger
        codec:ArtworkHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(queryArtworkId:completion:)], @"ArtworkHostApi api (%@) doesn't respond to @selector(queryArtworkId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api queryArtworkId:arg_id completion:^(FlutterStandardTypedData *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *PlayerHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void SetUpPlayerHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PlayerHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.startAllSongs"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startAllSongsIndex:error:)], @"PlayerHostApi api (%@) doesn't respond to @selector(startAllSongsIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSInteger arg_index = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        [api startAllSongsIndex:arg_index error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.play"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(playWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(playWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api playWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.pause"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pauseWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(pauseWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api pauseWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.prev"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(prevWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(prevWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api prevWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.next"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(nextWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(nextWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api nextWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.seek"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(seekTime:error:)], @"PlayerHostApi api (%@) doesn't respond to @selector(seekTime:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        double arg_time = [GetNullableObjectAtIndex(args, 0) doubleValue];
        FlutterError *error;
        [api seekTime:arg_time error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.getCurrentTime"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getCurrentTimeWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(getCurrentTimeWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api getCurrentTimeWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface SongHostApiCodecReader : FlutterStandardReader
@end
@implementation SongHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [Song fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface SongHostApiCodecWriter : FlutterStandardWriter
@end
@implementation SongHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[Song class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface SongHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation SongHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[SongHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[SongHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *SongHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    SongHostApiCodecReaderWriter *readerWriter = [[SongHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpSongHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SongHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.SongHostApi.getAllSongs"
        binaryMessenger:binaryMessenger
        codec:SongHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAllSongsWithError:)], @"SongHostApi api (%@) doesn't respond to @selector(getAllSongsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<Song *> *output = [api getAllSongsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.SongHostApi.getSongsByAlbumId"
        binaryMessenger:binaryMessenger
        codec:SongHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getSongsByAlbumIdAlbumId:error:)], @"SongHostApi api (%@) doesn't respond to @selector(getSongsByAlbumIdAlbumId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_albumId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSArray<Song *> *output = [api getSongsByAlbumIdAlbumId:arg_albumId error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface PlayerFlutterApiCodecReader : FlutterStandardReader
@end
@implementation PlayerFlutterApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [Song fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PlayerFlutterApiCodecWriter : FlutterStandardWriter
@end
@implementation PlayerFlutterApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[Song class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface PlayerFlutterApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PlayerFlutterApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PlayerFlutterApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PlayerFlutterApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PlayerFlutterApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PlayerFlutterApiCodecReaderWriter *readerWriter = [[PlayerFlutterApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface PlayerFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation PlayerFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onIsPlayingChangeIsPlaying:(BOOL)arg_isPlaying completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = @"dev.flutter.pigeon.thinmpf.PlayerFlutterApi.onIsPlayingChange";
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:PlayerFlutterApiGetCodec()];
  [channel sendMessage:@[@(arg_isPlaying)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onPlaybackSongChangeSong:(Song *)arg_song completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = @"dev.flutter.pigeon.thinmpf.PlayerFlutterApi.onPlaybackSongChange";
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:PlayerFlutterApiGetCodec()];
  [channel sendMessage:@[arg_song ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

