// Autogenerated from Pigeon (v21.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Album {
  var id: String
  var title: String
  var artist: String
  var imageId: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> Album? {
    let id = __pigeon_list[0] as! String
    let title = __pigeon_list[1] as! String
    let artist = __pigeon_list[2] as! String
    let imageId = __pigeon_list[3] as! String

    return Album(
      id: id,
      title: title,
      artist: artist,
      imageId: imageId
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      artist,
      imageId,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Artist {
  var id: String
  var artist: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> Artist? {
    let id = __pigeon_list[0] as! String
    let artist = __pigeon_list[1] as! String

    return Artist(
      id: id,
      artist: artist
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      artist,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Song {
  var id: String
  var title: String
  var artist: String
  var imageId: String
  var duration: Double

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> Song? {
    let id = __pigeon_list[0] as! String
    let title = __pigeon_list[1] as! String
    let artist = __pigeon_list[2] as! String
    let imageId = __pigeon_list[3] as! String
    let duration = __pigeon_list[4] as! Double

    return Song(
      id: id,
      title: title,
      artist: artist,
      imageId: imageId,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      artist,
      imageId,
      duration,
    ]
  }
}
private class AudioPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Album.fromList(self.readValue() as! [Any?])
    case 130:
      return Artist.fromList(self.readValue() as! [Any?])
    case 131:
      return Song.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AudioPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Album {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Artist {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Song {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AudioPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AudioPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AudioPigeonCodecWriter(data: data)
  }
}

class AudioPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AudioPigeonCodec(readerWriter: AudioPigeonCodecReaderWriter())
}


/// HostApi
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AlbumHostApi {
  func getAllAlbums() throws -> [Album]
  func getAlbumsByArtistId(artistId: String) throws -> [Album]
  func getAlbumById(id: String) throws -> Album?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AlbumHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AudioPigeonCodec.shared }
  /// Sets up an instance of `AlbumHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AlbumHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getAllAlbumsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.AlbumHostApi.getAllAlbums\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllAlbumsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllAlbums()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllAlbumsChannel.setMessageHandler(nil)
    }
    let getAlbumsByArtistIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.AlbumHostApi.getAlbumsByArtistId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAlbumsByArtistIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let artistIdArg = args[0] as! String
        do {
          let result = try api.getAlbumsByArtistId(artistId: artistIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAlbumsByArtistIdChannel.setMessageHandler(nil)
    }
    let getAlbumByIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.AlbumHostApi.getAlbumById\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAlbumByIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          let result = try api.getAlbumById(id: idArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAlbumByIdChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ArtistHostApi {
  func getAllArtists() throws -> [Artist]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ArtistHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AudioPigeonCodec.shared }
  /// Sets up an instance of `ArtistHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ArtistHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getAllArtistsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.ArtistHostApi.getAllArtists\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllArtistsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllArtists()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllArtistsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ArtworkHostApi {
  func queryArtwork(id: String, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ArtworkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AudioPigeonCodec.shared }
  /// Sets up an instance of `ArtworkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ArtworkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let queryArtworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.ArtworkHostApi.queryArtwork\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryArtworkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.queryArtwork(id: idArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryArtworkChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlayerHostApi {
  func startAllSongs(index: Int64) throws
  func startAlbumSongs(index: Int64, albumId: String) throws
  func startArtistSongs(index: Int64, artistId: String) throws
  func play() throws
  func pause() throws
  func prev() throws
  func next() throws
  func seek(time: Double) throws
  func getCurrentTime() throws -> Double
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlayerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AudioPigeonCodec.shared }
  /// Sets up an instance of `PlayerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlayerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startAllSongsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.startAllSongs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAllSongsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.startAllSongs(index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAllSongsChannel.setMessageHandler(nil)
    }
    let startAlbumSongsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.startAlbumSongs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAlbumSongsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let albumIdArg = args[1] as! String
        do {
          try api.startAlbumSongs(index: indexArg, albumId: albumIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAlbumSongsChannel.setMessageHandler(nil)
    }
    let startArtistSongsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.startArtistSongs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startArtistSongsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let artistIdArg = args[1] as! String
        do {
          try api.startArtistSongs(index: indexArg, artistId: artistIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startArtistSongsChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { _, reply in
        do {
          try api.play()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let prevChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.prev\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prevChannel.setMessageHandler { _, reply in
        do {
          try api.prev()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      prevChannel.setMessageHandler(nil)
    }
    let nextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.next\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      nextChannel.setMessageHandler { _, reply in
        do {
          try api.next()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      nextChannel.setMessageHandler(nil)
    }
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeArg = args[0] as! Double
        do {
          try api.seek(time: timeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    let getCurrentTimeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.PlayerHostApi.getCurrentTime\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentTimeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCurrentTime()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCurrentTimeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SongHostApi {
  func getAllSongs() throws -> [Song]
  func getSongsByArtistId(artistId: String) throws -> [Song]
  func getSongsByAlbumId(albumId: String) throws -> [Song]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SongHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AudioPigeonCodec.shared }
  /// Sets up an instance of `SongHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SongHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getAllSongsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.SongHostApi.getAllSongs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllSongsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllSongs()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllSongsChannel.setMessageHandler(nil)
    }
    let getSongsByArtistIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.SongHostApi.getSongsByArtistId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSongsByArtistIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let artistIdArg = args[0] as! String
        do {
          let result = try api.getSongsByArtistId(artistId: artistIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSongsByArtistIdChannel.setMessageHandler(nil)
    }
    let getSongsByAlbumIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.SongHostApi.getSongsByAlbumId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSongsByAlbumIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let albumIdArg = args[0] as! String
        do {
          let result = try api.getSongsByAlbumId(albumId: albumIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSongsByAlbumIdChannel.setMessageHandler(nil)
    }
  }
}
/// FlutterApi
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PlayerFlutterApiProtocol {
  func onIsPlayingChange(isPlaying isPlayingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPlaybackSongChange(song songArg: Song, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PlayerFlutterApi: PlayerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AudioPigeonCodec {
    return AudioPigeonCodec.shared
  }
  func onIsPlayingChange(isPlaying isPlayingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.thinmpf.PlayerFlutterApi.onIsPlayingChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isPlayingArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPlaybackSongChange(song songArg: Song, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.thinmpf.PlayerFlutterApi.onPlaybackSongChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([songArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
