// Autogenerated from Pigeon (v16.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HostPermissionApi {
  func requestPermission() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HostPermissionApiSetup {
  /// The codec used by HostPermissionApi.
  /// Sets up an instance of `HostPermissionApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HostPermissionApi?) {
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.HostPermissionApi.requestPermission", binaryMessenger: binaryMessenger)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        do {
          try api.requestPermission()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
  }
}
