// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by HostPlayerApi.
NSObject<FlutterMessageCodec> *HostPlayerApiGetCodec(void);

@protocol HostPlayerApi
- (void)playWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpHostPlayerApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HostPlayerApi> *_Nullable api);

NS_ASSUME_NONNULL_END
