// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Player.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface PlaybackState ()
+ (PlaybackState *)fromList:(NSArray *)list;
+ (nullable PlaybackState *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation PlaybackState
+ (instancetype)makeWithIsPlaying:(BOOL )isPlaying {
  PlaybackState* pigeonResult = [[PlaybackState alloc] init];
  pigeonResult.isPlaying = isPlaying;
  return pigeonResult;
}
+ (PlaybackState *)fromList:(NSArray *)list {
  PlaybackState *pigeonResult = [[PlaybackState alloc] init];
  pigeonResult.isPlaying = [GetNullableObjectAtIndex(list, 0) boolValue];
  return pigeonResult;
}
+ (nullable PlaybackState *)nullableFromList:(NSArray *)list {
  return (list) ? [PlaybackState fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    @(self.isPlaying),
  ];
}
@end

@interface PlayerHostApiCodecReader : FlutterStandardReader
@end
@implementation PlayerHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [PlaybackState fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PlayerHostApiCodecWriter : FlutterStandardWriter
@end
@implementation PlayerHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PlaybackState class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface PlayerHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PlayerHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PlayerHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PlayerHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PlayerHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PlayerHostApiCodecReaderWriter *readerWriter = [[PlayerHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpPlayerHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PlayerHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.startBySongs"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startBySongsIndex:error:)], @"PlayerHostApi api (%@) doesn't respond to @selector(startBySongsIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSInteger arg_index = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        [api startBySongsIndex:arg_index error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.play"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(playWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(playWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api playWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.stop"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(stopWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.thinmpf.PlayerHostApi.getPlaybackState"
        binaryMessenger:binaryMessenger
        codec:PlayerHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPlaybackStateWithError:)], @"PlayerHostApi api (%@) doesn't respond to @selector(getPlaybackStateWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        PlaybackState *output = [api getPlaybackStateWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *PlayerFlutterApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

@interface PlayerFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation PlayerFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)playbackStateChangeStr:(NSString *)arg_str completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = @"dev.flutter.pigeon.thinmpf.PlayerFlutterApi.playbackStateChange";
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:PlayerFlutterApiGetCodec()];
  [channel sendMessage:@[arg_str ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

