// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Song {
  var id: String
  var title: String
  var artist: String
  var imageId: String

  static func fromList(_ list: [Any?]) -> Song? {
    let id = list[0] as! String
    let title = list[1] as! String
    let artist = list[2] as! String
    let imageId = list[3] as! String

    return Song(
      id: id,
      title: title,
      artist: artist,
      imageId: imageId
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      artist,
      imageId,
    ]
  }
}
private class SongHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return Song.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SongHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Song {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SongHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SongHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SongHostApiCodecWriter(data: data)
  }
}

class SongHostApiCodec: FlutterStandardMessageCodec {
  static let shared = SongHostApiCodec(readerWriter: SongHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SongHostApi {
  func findAll() throws -> [Song]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SongHostApiSetup {
  /// The codec used by SongHostApi.
  static var codec: FlutterStandardMessageCodec { SongHostApiCodec.shared }
  /// Sets up an instance of `SongHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SongHostApi?) {
    let findAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.thinmpf.SongHostApi.findAll", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      findAllChannel.setMessageHandler { _, reply in
        do {
          let result = try api.findAll()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      findAllChannel.setMessageHandler(nil)
    }
  }
}
